# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(bsicons)
library(fansi)
library(leaflet)
library(lorem)
library(rhino)
library(sever)
library(sf)
library(shinyFeedback)
library(shinyWidgets)
library(treesitter)
library(treesitter.r)
library(httr2)
library(giscoR)
library(shinyjs)
library(reactable)
library(shinylogs)